apiVersion: v1
kind: Service
metadata:
  name: exam-backend-svc
  namespace: exam-platform
  labels:
    app: exam-backend
spec:
  selector:
    app: exam-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
